# Generated by Django 3.2.16 on 2023-07-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230715_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_date',
        ),
    ]
